### PR TITLE
feat:增加景點頁面，首頁點擊景點圖可連結至景點頁面，點選左上標題回首頁

### PR DESCRIPTION
**Pull request by yslsy**
name:王薇
http://54.219.37.158:3000/
http://54.219.37.158:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your APIs are borken, try to find out the root cause and fix it.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Color of separator lines should be lighter. Height of separator lines should be only 1px.
2. Padding of date input should not be 0px.
3. Suggest following mobile design for any devices where screen width<500px.

**Comment by yslsy** [comment]
Problems have been fixed.
http://54.219.37.158:3000/
http://54.219.37.158:3000/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
