### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by yslsy**
名字:王薇
http://54.219.37.158:3000/api/attractions?page=1
http://54.219.37.158:3000/api/attractions?page=0&keyword=藝文館所
http://54.219.37.158:3000/api/attractions?page=0&keyword=北
http://54.219.37.158:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done but response format of http://54.219.37.158:3000/api/attraction/10 is incorrent.

Fix it and re-request review.

**Comment by yslsy** [comment]
名字:王薇
http://54.219.37.158:3000/api/attraction/10
Already fixed the response format, please re-review it, thank you

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
